# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20191015_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_name',
            new_name='password',
        ),
    ]
